/*
 *  File: __dataFixtureName__
 *  Generated by: Mongoose-Fixture (v__version__)
 *
 */


var ParentFixture = require('../fixtures/ParentFixture').ParentFixture;
/*
in case of a parent fixture (has_many relation)
a new mongodb _id can be pre-generated via
var ObjectID = require('mongoose').mongo.BSONNative.ObjectID;

..
parent1 : {
    _id: new ObjectID(),
    ...
}
 */
     
module.exports.__dataFixtureName__ = {
    __dataFixtureName__1: {
        _id:ParentFixture.parent1._id,
        // by not defining an _id mongoose-fixture
        // will by default set a mongo ObjectID
        // setting on manually will override mongoDB
        name:'Some Test Data',
        tags:['test','data']
    }
    , __dataFixtureName__2: {
        _id:ParentFixture.parent2._id,
        name:'More Test Data',
        tags:['test','data','more']
    }
};
